[book]
authors = ["Dubs"]
language = "en"
multilingual = false
src = "src"
title = "SwapDex Network Documentation"

[output.html]
default-theme = "navy"
git-repository-url = "https://github.com/Swapdex-Protocol/documentation"
git-repository-icon = "fa-github"